#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
python3 gen_cwl.py ../sty/profnsi.sty --out profnsi.cwl
"""

import re
import argparse
from pathlib import Path

HEADER = """# profnsi.cwl
# Generated automatically from profnsi.sty
# Put this file in TeXstudio completion/user or completion/autogenerated
"""

def balanced_braces(s, i):
    """Return (content, new_index) where s[i] == '{'."""
    assert s[i] == '{'
    depth = 0
    start = i + 1
    j = i
    while j < len(s):
        if s[j] == '{':
            depth += 1
        elif s[j] == '}':
            depth -= 1
            if depth == 0:
                return s[start:j], j + 1
        j += 1
    raise ValueError("Unbalanced braces")

def tokenize_xparse_spec(spec):
    tokens = []
    i = 0
    while i < len(spec):
        c = spec[i]
        if c.isspace():
            i += 1
            continue

        if c in ("m", "o", "s", "g"):
            tokens.append(c)
            i += 1
            continue

        if c in ("O", "d", "D", "r", "R", "t", "e", "E"):
            tok = c
            i += 1
            # absorb following brace groups if present
            while i < len(spec) and spec[i].isspace():
                i += 1
            while i < len(spec) and spec[i] == "{":
                _, i = balanced_braces(spec, i)
                tok += "{}"
                while i < len(spec) and spec[i].isspace():
                    i += 1
            tokens.append(tok)
            continue

        # unknown char/token, skip
        i += 1
    return tokens

def spec_to_signature(spec):
    tokens = tokenize_xparse_spec(spec)
    out = []
    mand_i = 1
    opt_i = 1
    for tok in tokens:
        if tok == "s":
            out.append("*")
        elif tok in ("o", "O{}"):
            out.append(f"[%<opt{opt_i}%>]")
            opt_i += 1
        elif tok in ("m", "g", "r{}", "R{}{}", "e{}", "E{}{}"):
            out.append(f"{{%<arg{mand_i}%>}}")
            mand_i += 1
        elif tok in ("d{}", "D{}{}"):
            out.append(f"[%<opt{opt_i}%>]")
            opt_i += 1
        elif tok == "t{}":
            out.append("*")
        else:
            out.append(f"{{%<arg{mand_i}%>}}")
            mand_i += 1
    return "".join(out)

def newcommand_signature(n_args, opt_default=None):
    n = int(n_args or 0)
    out = []
    if opt_default is not None:
        out.append("[%<opt1%>]")
        for i in range(2, n + 1):
            out.append(f"{{%<arg{i-1}%>}}")
    else:
        for i in range(1, n + 1):
            out.append(f"{{%<arg{i}%>}}")
    return "".join(out)

def add_command(cmds, name, sig="", suffix=""):
    name = name.strip()
    if not name:
        return
    line = "\\" + name + sig + suffix
    cmds.add(line)

def add_environment(cmds, envname, sig=""):
    envname = envname.strip()
    if not envname:
        return
    cmds.add(r"\begin{" + envname + "}" + sig)
    cmds.add(r"\end{" + envname + "}")

def parse_newcommands(text, cmds):
    # \newcommand{\foo}[2][default]{...}
    pat = re.compile(
        r'\\(?:newcommand|renewcommand|providecommand)\*?\s*'
        r'\{\\([A-Za-z@]+)\}'
        r'(?:\[(\d+)\])?'
        r'(?:\[(.*?)\])?',
        flags=re.S
    )
    for m in pat.finditer(text):
        name, n_args, opt_default = m.groups()
        sig = newcommand_signature(n_args, opt_default)
        add_command(cmds, name, sig)

def parse_xparse_commands(text, cmds):
    pat = re.compile(
        r'\\(?:NewDocumentCommand|RenewDocumentCommand|ProvideDocumentCommand)\s*',
        flags=re.S
    )

    for m in pat.finditer(text):
        i = m.end()

        while i < len(text) and text[i].isspace():
            i += 1

        if i >= len(text) or text[i] != '{':
            continue
        name, i = balanced_braces(text, i)
        name = name.strip().lstrip('\\')

        while i < len(text) and text[i].isspace():
            i += 1

        if i >= len(text) or text[i] != '{':
            continue
        spec, i = balanced_braces(text, i)

        sig = spec_to_signature(spec)
        add_command(cmds, name, sig)

def parse_new_environments(text, cmds):
    # \lstnewenvironment{python}[1][]{...}{...}
    pat1 = re.compile(
        r'\\lstnewenvironment\s*'
        r'\{([A-Za-z*@]+)\}'
        r'(?:\[(\d+)\])?'
        r'(?:\[(.*?)\])?',
        flags=re.S
    )
    for m in pat1.finditer(text):
        name, n_args, opt_default = m.groups()
        sig = newcommand_signature(n_args, opt_default)
        add_environment(cmds, name, sig)

    # \newtcolorbox{box}[1][]{...}
    pat2 = re.compile(
        r'\\newtcolorbox\s*'
        r'\{([A-Za-z*@]+)\}'
        r'(?:\[(\d+)\])?'
        r'(?:\[(.*?)\])?',
        flags=re.S
    )
    for m in pat2.finditer(text):
        name, n_args, opt_default = m.groups()
        sig = newcommand_signature(n_args, opt_default)
        add_environment(cmds, name, sig)

    # \NewDocumentEnvironment{env}{m O{} O{}}{...}{...}
    pat3 = re.compile(
        r'\\(?:NewDocumentEnvironment|RenewDocumentEnvironment|ProvideDocumentEnvironment)\s*',
        flags=re.S
    )
    for m in pat3.finditer(text):
        i = m.end()

        while i < len(text) and text[i].isspace():
            i += 1

        if i >= len(text) or text[i] != '{':
            continue
        name, i = balanced_braces(text, i)
        name = name.strip()

        while i < len(text) and text[i].isspace():
            i += 1

        if i >= len(text) or text[i] != '{':
            continue
        spec, i = balanced_braces(text, i)

        sig = spec_to_signature(spec)
        add_environment(cmds, name, sig)

def parse_doc_blocks(text, cmds):
    # Optional support for your % --- doc ... % --- end-doc blocks
    blocks = re.findall(r'% --- doc(.*?)% --- end-doc', text, flags=re.S)
    for block in blocks:
        name = None
        kind = None
        args = {}
        for line in block.splitlines():
            s = line.lstrip('%').strip()
            if not s:
                continue
            if s.startswith('name:'):
                name = s.split(':', 1)[1].strip().lstrip('\\')
            elif s.startswith('kind:'):
                kind = s.split(':', 1)[1].strip()
            elif s.startswith('spec:'):
                args['spec'] = s.split(':', 1)[1].strip()
            elif s.startswith('num:'):
                args['num'] = s.split(':', 1)[1].strip()
            elif s.startswith('opt_default:'):
                args['opt_default'] = s.split(':', 1)[1].strip()

        if not name or not kind:
            continue

        if kind in ('NewDocumentCommand', 'newdocumentcommand'):
            sig = spec_to_signature(args.get('spec', ''))
            add_command(cmds, name, sig)
        elif kind in ('newcommand', 'providecommand', 'renewcommand'):
            sig = newcommand_signature(args.get('num', '0'), args.get('opt_default'))
            add_command(cmds, name, sig)

def render_cwl(cmds):
    lines = [HEADER.strip(), ""]
    for line in sorted(cmds, key=lambda s: s.lower()):
        lines.append(line)
    lines.append("")
    return "\n".join(lines)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("input_sty", help="Chemin vers le fichier .sty")
    ap.add_argument("--out", default="profnsi.cwl", help="Nom du fichier .cwl généré")
    args = ap.parse_args()

    text = Path(args.input_sty).read_text(encoding="utf-8", errors="ignore")

    cmds = set()
    parse_doc_blocks(text, cmds)
    parse_newcommands(text, cmds)
    parse_xparse_commands(text, cmds)
    parse_new_environments(text, cmds)

    Path(args.out).write_text(render_cwl(cmds), encoding="utf-8")
    print("OK:", args.out)

if __name__ == "__main__":
    main()